import Foundation

class WebColors {
    static var blue:String = "blue"
    static var fuchsia:String = "fuchsia"
    static var black:String = "black"
    static var gray:String = "gray"
    static var grey:String = "grey"
    static var silver:String = "silver"
    static var maroon:String = "maroon"
    static var red:String = "red"
    static var orange:String = "orange"
    static var yellow:String = "yellow"
    static var olive:String = "olive"
    static var green:String = "green"
    static var teal:String = "teal"
    static var lime:String = "lime"
    static var aqua:String = "aqua"
    static var navy:String = "navy"
    static var purple:String = "purple"
    static var white:String = "white"
    static var grey1:String = "grey1"
    static var grey2:String = "grey2"
    static var grey3:String = "grey3"
    static var grey4:String = "grey4"
    static var grey5:String = "grey5"
    static var grey6:String = "grey6"
    static var grey7:String = "grey7"
    static var grey8:String = "grey8"
    static var grey9:String = "grey9"
    static var white1:String = "white1"
    static var white2:String = "white2"
    static var white3:String = "white3"
    static var white4:String = "white4"
    static var white5:String = "white5"
    static var white6:String = "white6"
    static var white7:String = "white7"
    static var white8:String = "white8"
    static var white9:String = "white9"
    static var webColors:[String] = [WebColors.blue,WebColors.fuchsia,WebColors.black,WebColors.gray,WebColors.grey,WebColors.silver,WebColors.maroon,WebColors.red,WebColors.orange,WebColors.yellow,WebColors.olive,WebColors.green,WebColors.teal,WebColors.lime,WebColors.aqua,WebColors.navy,WebColors.purple,WebColors.white,WebColors.grey1,WebColors.grey2,WebColors.grey3,WebColors.grey4,WebColors.grey5,WebColors.grey6,WebColors.grey7,WebColors.grey8,WebColors.grey9,WebColors.white1,WebColors.white2,WebColors.white3,WebColors.white4,WebColors.white5,WebColors.white6,WebColors.white7,WebColors.white8,WebColors.white9]
}
